### PR TITLE
Fix/Add all MW channel properties

### PR DESCRIPTION
**Pull request by nulinspiratie**
This PR adds the following changes
- Add missing attributes to `MWChannel`
- Make `Channel` an abstract base class
- Move `intermediate_frequency` to `Channel`, meaning that all channels share this property
- Add `smearing`, `time_of_flight`

### CODE REVIEW

**Comment by deanpoulos** [comment]
Hey Serwan, the attributes look good, but it looks like the `MWChannel` is missing the API for creating QUA commands, e.g., 
```python
AttributeError: 'InOutMWChannel' object has no attribute 'measure'
```
These currently live in e.g., the IQChannel class. Perhaps you could put a separate class which contains just the interface for creating QUA command and have both `InOutIQchannel` and InOutMWChannel` inherit from this.

**Comment by deanpoulos** [comment]
Another thing is that it wont allow you to add IQ waveforms unless it is an `IQChannel`, but you should also be able to add IQWaveforms to an MWChannel. So in 
`quam/components/pulses.py`, you could add something like:
```diff
                 channel type (SingleChannel, IQChannel, InOutIQChannel).
         """
 
-        from quam.components.channels import SingleChannel, IQChannel
+        from quam.components.channels import SingleChannel, IQChannel, MWChannel
 
         pulse_config = config["pulses"][self.pulse_name]
 
@@ -221,7 +221,7 @@ class Pulse(QuamComponent):
                 "Waveform type 'single' not allowed for IQChannel"
                 f" '{self.channel.name}'"
             )
-        elif "I" in waveforms and not isinstance(self.channel, IQChannel):
+        elif "I" in waveforms and not isinstance(self.channel, (IQChannel, MWChannel)):
             raise ValueError(
                 "Waveform type 'IQ' not allowed for SingleChannel"
                 f" '{self.channel.name}'"
```

**Review by deanpoulos — CHANGES_REQUESTED** [review]
Hey Serwan, the attributes look good, but it looks like the `MWChannel` is missing the API for creating QUA commands, e.g., 
```python
AttributeError: 'InOutMWChannel' object has no attribute 'measure'
```
These currently live in e.g., the IQChannel class. Perhaps you could put a separate class which contains just the interface for creating QUA command and have both `InOutIQchannel` and InOutMWChannel` inherit from this.

**Review by deanpoulos — CHANGES_REQUESTED** [review]
Another thing is that it wont allow you to add IQ waveforms unless it is an `IQChannel`, but you should also be able to add IQWaveforms to an MWChannel. So in 
`quam/components/pulses.py`, you could add something like:
```diff
                 channel type (SingleChannel, IQChannel, InOutIQChannel).
         """
 
-        from quam.components.channels import SingleChannel, IQChannel
+        from quam.components.channels import SingleChannel, IQChannel, MWChannel
 
         pulse_config = config["pulses"][self.pulse_name]
 
@@ -221,7 +221,7 @@ class Pulse(QuamComponent):
                 "Waveform type 'single' not allowed for IQChannel"
                 f" '{self.channel.name}'"
             )
-        elif "I" in waveforms and not isinstance(self.channel, IQChannel):
+        elif "I" in waveforms and not isinstance(self.channel, (IQChannel, MWChannel)):
             raise ValueError(
                 "Waveform type 'IQ' not allowed for SingleChannel"
                 f" '{self.channel.name}'"
```

**Comment by nulinspiratie** [comment]
Addressed both issues, @deanpoulos wdyt?

**Pull request merged**
